__version__ = '1.14.1'
__codename__ = 'Final Frontier'
__author__ = '@s0lst1c3'
__contact__ = 'gabriel<<at>>transmitengage.com'
__tagline__ = 'Now with more fast travel than a next-gen Bethesda game. >:D'
