#!/usr/bin/env python
import os
import config

def read_deps_file(deps_file):
    with open(deps_file) as fd:
        return ' '.join([ line.strip() for line in fd ])

if __name__ == '__main__':

    if raw_input('Do you want update your package list ("apt -y update")(recommended)? [y/N]: ').lower() == 'y':
        print '\n[*] Downloading package lists from kali repositories...\n'
        os.system('apt -y update')
    print '\n[*] complete!\n'

    if raw_input('Do you want upgrade your package list ("apt -y upgrade")(recommended)? [y/N]: ').lower() == 'y':
        print '\n[*] Performing upgrade...\n'
        os.system('apt -y upgrade')
    print '\n[*] complete!\n'

    print '\n[*] Installing Kali dependencies...\n'
    os.system('apt -y install %s' % read_deps_file('kali-dependencies.txt'))
    print '\n[*] complete!\n'

    print '\n[*] Installing Python dependencies...\n'
    os.system('pip install -r pip.req')
    print '\n[*] complete!\n'


    print '\n[*] Compiling hostapd...\n'
    os.system("cd %s && make" % config.hostapd_dir)
    print '\n[*] complete!\n'

    print '\n[*] Downloading default wordlist...\n'
    os.system("wget %s -O %s.tar.gz" % (config.wordlist_source, config.default_wordlist))
    print '\n[*] complete!\n'

    print '\n[*] Extracting default wordlist...\n'
    os.system("cd %s && tar xzf %s.tar.gz" % (config.wordlist_dir, config.default_wordlist))
    print '\n[*] complete!\n'
